### ISSUE TITLE
PhpStorm .idea directory: add to repository?

### ISSUE THREAD

**Issue by Fonata** [parsecsv/parsecsv-for-php#101]
Dear @jimeh, @repat, @helpse, @Norcoen, @waknauss-kingdom, @williamknauss  

I'd like to add the ``.idea`` directory to the repository. It will tell the PhpStorm IDE how to format the code, which inspections to skip and some other things. 

I propose to vote on this until the end of the year (2017-12-31). 

Write +1 if you are in favor, and -1 if you'd like to keep the repository IDE-vendor-agnostic. Feel free to document why you feel a certain way, but that's no must.

**Comment by adrianbj** [comment]
What about being more inclusive and using: http://editorconfig.org/

**Comment by Fonata** [comment]
Indeed, this is what I had in mind, too - in case the PhpStorm doesn't win any comments here. I'll go ahead and open a merge request regardless how this issue turns out.

**Comment by kingdominc** [comment]
I'm not a big fan of using IDEs for PHP development. With that said I am by no means discouraging anyone who does use them. (I use Sublime Text because of lack of funding for "cool" ideas like Zend Studio, etc). I am 100% ok with you adding the .idea file to the repo. However we want to be cautious not to add to many "IDE specific" files. 

@Fonata - I love how you from the get go are embracing open source democarcy and allow interested project members to vote. Keep this up!!!!

Final vote: +1

**Comment by williamknauss** [comment]
Sorry commented on the wrong account - deleting the comment by @kingdominc ....

I'm not a big fan of using IDEs for PHP development. With that said I am by no means discouraging anyone who does use them. (I use Sublime Text because of lack of funding for "cool" ideas like Zend Studio, etc). I am 100% ok with you adding the .idea file to the repo. However we want to be cautious not to add to many "IDE specific" files. 

@Fonata - I love how you from the get go are embracing open source democarcy and allow interested project members to vote. Keep this up!!!!

Final vote: +1

**Comment by adrianbj** [comment]
> However we want to be cautious not to add to many "IDE specific" files.

Sorry, I know I am a bit of an outsider here, but that is why I suggested a .editorconfig file. PHPStorm supports it: https://plugins.jetbrains.com/plugin/7294-editorconfig as does SublimeText and most other editors/IDEs - it' s really great way to handle things IMO.

**Comment by Fonata** [comment]
Thanks for your input! .editorconfig has been added! 

For anyone who wants my additional choice of settings, e.g. of disabled inspections and code style settings that fit to the current source code formatting, I just attach my [IntelliJ and PhpStorm settings.zip](https://github.com/parsecsv/parsecsv-for-php/files/1608617/IntelliJ.and.PhpStorm.settings.zip)
to this issue and close it. For a single-file library, the weight of another set of 9 files for a single vendor's IDEs doesn't seem right.
