### ISSUE TITLE
PHP 7.2: count arg must be an array

### ISSUE THREAD

**Issue by geminorum** [parsecsv/parsecsv-for-php#116]
parsecsv.lib.php:353 `count(): Parameter must be an array or an object that implements Countable`

**Comment by geminorum** [comment]
composer version: `0.4.5`

**Comment by Fonata** [comment]
Thanks @geminorum for bringing this up. The message was caused by the line `if ( count($conditions) > 0 ) {` which was replaced by `if (!is_null($conditions)) {` in the master branch. 

There is no released version fixing this. I'm quite confident the next official release is not more than 4 weeks away.

**Comment by shawe** [comment]
@Fonata thanks for say the ETA for next release, I'm also waiting for it.

**Comment by Fonata** [comment]
Feel free to use the `master` branch until then.

**Comment by shawe** [comment]
I do it, and works well, but the main maintener don't want to use dev-master in composer.

**Comment by Fonata** [comment]
I just published the 1.0.0 release. Now you can update the version number in your `composer.json` to get it.

Thank you for your patience. Feel free to create more issues.

**Comment by shawe** [comment]
Thanks to keep up the good work ;)
