### ISSUE TITLE
output csv without header

### ISSUE THREAD

**Issue by camelG** [parsecsv/parsecsv-for-php#160]
Hi,i want output a csv file without header by frollow code,but just get a error...

        $output = new ParseCsv\Csv();
        $output->output('ver2.csv', array_values($req_data), [], ',');

**Comment by camelG** [comment]
> 
> 
> Hi, what is the error message?


undefined offset $header? error below
========================
A PHP Error was encountered

Severity: Notice

Message: Undefined offset: 0

Filename: src/Csv.php

Line Number: 824

Backtrace:

File: C:\xampp\htdocs\csv.com\application\vendor\parsecsv\php-parsecsv\src\Csv.php
Line: 824
Function: _error_handler

File: C:\xampp\htdocs\csv.com\application\vendor\parsecsv\php-parsecsv\src\Csv.php
Line: 441
Function: unparse

File: C:\xampp\htdocs\csv.com\application\controllers\Csv.php
Line: 99
Function: output

File: C:\xampp\htdocs\csv.com\public_html\index.php
Line: 315
Function: require_once

**Comment by Fonata** [comment]
@camelG What is the content of `$req_data`? Feel free to reduct, we just need to know the structure.

Thanks.

**Comment by camelG** [comment]
No problem for program,just my miss.
Thank you

**Comment by stevleibelt** [comment]
@camelG so the issue is solved?
If so, could you be so kind and tell what was the issue, how you've figured it out?

To motivate you, the benefit of your answer could be:

* Help other persons to find their issues faster next time
* Maybe give the developers a hint how to ease up error communication with the developer
* Even more but less likely, create a feature out for your issue

Best regards,
Stev
