### ISSUE TITLE
parse_string is protected

### ISSUE THREAD

**Issue by dnicastro** [parsecsv/parsecsv-for-php#165]
Following the documentation for  method parse_string:

>   /**
     * Parse CSV strings to arrays. If you need BOM detection or character
     * encoding conversion, please call load_data() first, **_followed by a call to
     * parse_string() with no parameters_**.
     *
     * ......
     */
    protected function parse_string($data = null) {

Should the documentation be updated?
parse_string() is a protected function

**Comment by Fonata** [comment]
We marked the parse_string() function as protected because its name looked like something to call when you want to, well, parse a string. We will update the code comments.

Let's assume your data sits in a variable `$your_data_string` and the ParseCsv object is called `$csv`. If you need BOM detection or character encoding conversion, please write your code like this:
``if ($csv->load_data($your_data_string)) $csv->parse($csv->file_data);``.
