### ISSUE TITLE
Keep linebreak as \n or <br />

### ISSUE THREAD

**Issue by antoine1003** [parsecsv/parsecsv-for-php#196]
Hi,

I use this tool to easily read csv file. In some files I have cells that contain line breaks : 

```csv
id;name;description
12:Josh;This name
is pretty cool
13;Molly; Owner of the shop.
Arrived in 2020
```

But the line breaks are removed. It could be cool to add a feature that allows the user to replace line break (expected final line break) by a given text.

Thanks,
Antoine

**Comment by Fonata** [comment]
For line breaks in CSV files you need to enclose the cell content. Most typically, the `"` character is used. 

I don't think that there is code in this library that removes line breaks. Do you have a source code example? Maybe it is just the visual display in the browser or the lack of enclosing characters.

**Comment by stevleibelt** [comment]
@antoine1003 is the answer provided by @fonata good enough to fix your issue?

This ticket is pretty old already and it would be nice to close it with a remark that the answer from @fonata was a good one.

**Comment by antoine1003** [comment]
I'll try to find in my old project 😄

**Comment by jimeh** [comment]
Input fields containing any form of line break, must be enclosed with double quotes. Otherwise it's impossible to reliable tell if the line break denotes a new record, or just a line break in the current field being parsed.

A bit more detail is available in clause 7 in my [csv-spec.org](https://csv-spec.org/) project:

> _7. Fields containing line breaks (CRLF, LF, or CR), double quotes, or the delimiter character (normally a comma) MUST be enclosed in double-quotes._

To use the original example in this issue:

```
id;name;description
12:Josh;This name
is pretty cool
13;Molly; Owner of the shop.
Arrived in 2020
```

It must be be changed to this to be parsable as CSV-structured data:

```
id;name;description
12:Josh;"This name
is pretty cool"
13;Molly;" Owner of the shop.
Arrived in 2020"
```

Which should then parse to the following structure if represented as JSON:

```json
[
  [
    "id",
    "name",
    "description"
  ],
  [
    "12",
    "Josh",
    "This name\nis pretty cool"
  ],
  [
    "13",
    "Molly",
    " Owner of the shop.\nArrived in 2020"
  ]
]
```

And if using the first record as a headers record, the above structure can be normalized to the following:

```json
[
  {
    "id": "12",
    "name": "Josh",
    "description": "This name\nis pretty cool"
  },
  {
    "id": "13",
    "name": "Molly",
    "description": " Owner of the shop.\nArrived in 2020"
  }
]
```
