### ISSUE TITLE
function parse_string() and unicode files

### ISSUE THREAD

**Issue by Norcoen** [parsecsv/parsecsv-for-php#38]
I don't have any data at hand to test it, but I spent some time playing around with the parse_string()-function for my chunk reader and think that it might fail if the csv file uses [unicode line terminators](http://en.wikipedia.org/wiki/Newline#Unicode).

Maybe more problems could occur from iterating $data[ ] as single characters, not taking care of multibyte characters.

Any thoughts?

**Comment by RatkoR** [comment]
Hi all,

I had the same problem. I have a csv file with multiple unicode characters. What is wrong is exactly what Norcoen has explained:

`$ch = (isset($data{$i})) ? $data{$i} : false` splits string one byte at a time. So when there is a multibyte characters it makes an error.

Because of this `parse_string` does not parse whole csv data:
`$strlen = strlen($data);` counts number of characters. The main `for` loop repeats it's cycle `$strlen` times. Because `$data{$i}` extracts a byte every loop (and not character) it doesn't loop through all cvs data.

An example: 
let's say we have a string with 3 characters ("a") and one multibyte character ("š"): "aaša".
`$strlen` would equal 4. The `for` loop would repeat 4 times:
Loop 1 would process the first byte of string ("a")
Loop 2 would process the second byte ("a")
Loop 3 would process the third byte (the first byte of multibyte character "š")
Loop 4 would process the forurth byte (the second byte of multibyte character "š")
Loop doesn't process the final "a" character.

We fixed it by first splitting string into characters:

```
        for( $idx = 0; $idx < $strlen; $idx++)
        { 
          $chars[] = mb_substr($data, $idx, 1);
        }
```

and then using this `$chars` array to get the `$ch`, `$nch` and `$pch` characters.

**Comment by Norcoen** [comment]
I just realized I did not do anything to solve my customers CSV problems for nearly 2 years :laughing:

@RatkoR you are wrong about _strlen _counting characters, it's clearly stated in the docs that _strlen_ counts bytes. Your example would return a length of 5 (I tested it)

Nevertheless I still think parsing the data should use mb_ oder iconv_ functions because line-endings might differ and (I don't remember the code) you might get into trouble if you split a string at/within multi-byte characters.

**Comment by RatkoR** [comment]
Not if one has `mbstring.func_overload` activated. In this case `strlen` returns number of characters, not bytes (which is what we have).

It works fine for my case if I break csv per characters (not per bytes).

**Comment by susgo** [comment]
Is this still relevant?

**Comment by Norcoen** [comment]
Never got around to test this again, so I can't say :cry:
