### ISSUE TITLE
Single column, numerical CSV

### ISSUE THREAD

**Issue by jatazoulja** [parsecsv/parsecsv-for-php#55]
Parsing issue when csv are numerical and has only one column.
ex:

86545235689
34365587654
13469874576

Somehow, it seperate each row base on the integer '6'.

I believe this was cause by having $enclosure = '"';
and requires all CSV to be enclose...

**Comment by Fonata** [comment]
Indeed, until 4e6448d2123e0c7f5405069f7b5512a52ae767d8 the function `_guess_delimiter()` used to return 6 for this example. This was because even though numbers are contained within `$auto_non_chars`, the `preg_quote` call quoted the `-` character into ``\n` to build this: ``/[a\-zA\-Z0\-9]\\n\\r/i``. As it refutes the objective of `$auto_non_chars`, I consider a delimiter of int(6) a bug. 

However, because of commit 1321c3b693d0049ef5613c0048d8f8de67a21264, the orignal buggy behavior was fixed already, because 
- ``'6' == int(6) `` is true
- ``'6' === int(6)`` is false

Also see issue #61 and #99.
