### ISSUE TITLE
encoding issue when parsing chines/arabic 

### ISSUE THREAD

**Issue by tahseen2k8** [parsecsv/parsecsv-for-php#81]
Hi there 
I am using this library from last 2 years very easy to use and control 
thanks for such a useful tool .
currently I am facing an issue in parsCSV. i need to parse arabic and chines data from sheet 
and the library showing me only ?????? like this 
obsessively I had tried both method auto and encode but not showing the data exactly what i want any urgent suggestion or help will highly appreciated from my side 
Thanks ,

**Comment by Fonata** [comment]
Sorry we weren't of help earlier. I'll close this issue now because so much time has passed.

From the information you provided I'd guess that ``mb_detect_encoding`` or the BOM detection from #106 could help. You can also try to figure out the encoding using Open Office.

Feel free to open it again in case you still have problems.
