### ISSUE TITLE
->auto() delimiter detection does not account for offset

### ISSUE THREAD

**Issue by isleshocky77** [parsecsv/parsecsv-for-php#86]
If I have a file that looks like the following.

```
Summary
First,Last,Age
John,Smith,10
Billy,Bob,9
Jane,Fine,14
Jim,Stark,12
```

| A | B | C |
| --- | --- | --- |
| Summary |  |  |
| First | Last | Age |
| John | Smith | 10 |
| Billy | Bob | 9 |
| Jane | Fine | 14 |
| Jim | Stark | 12 |

And then pass it to parseCsv with an offset.

``` php
$parseCsv = new \parseCsv($file, 2);
```

then parseCsv is unable to determine the delimiter

``` php
$delimiter = $parseCsv->auto(); // returns false
```

the reason for this is that `auto` does not account for offset which ends up sending the first row to `_check_count` which sees that `,` is not represented on every line and immediately returned as false.

I'm guessing someone will say that this is not a valid CSV file. And according to RFC 4180, it isn't.

> Each line should contain the same number of fields throughout the file. 

However, everyone knows that there are a lot of different implementations of the CSV and it would be nice if we could allow for this case of considering the offset in delimiter detection.

**Comment by Fonata** [comment]
I'm drawn to say: use your knowledge of the file to help parseCSV: 
- call `parse` instead of `auto` to keep the default delimiter (which is `,`), or
- remove the first line before handing the string over to parseCSV

I'll close this issue for now. If there is a larger number or important source for such 'broken' files, we'll have a name for the 'brokeness'. Then, feel free to open this issue again.
