### ISSUE TITLE
Open URLs with ParseCSV

### ISSUE THREAD

**Issue by alehandrof** [parsecsv/parsecsv-for-php#92]
Is it possible to open remote CSVs with this class?

I tried something like this: `$csv  = new parseCSV('http://example.com/foo.csv');` but no joy. Is there another built-in way of approaching this?

**Comment by Fonata** [comment]
Short answer: no, parseCSV will never support URLs directly. 

They are not treated specially. In particular, there is a call to `file_exists` around line 826 that will always fail because [stat is not supported for http(s)](http://us3.php.net/manual/en/wrappers.http.php).

If your PHP is configured to allow reading from http via stream wrappers, you can run any file function to get the content first, e.g.

````php
$content = file_get_contents('http://example.com/foo.csv');
$csv = new parseCSV($content);
````

Otherwise, you'd have to use the operating system or PHP's cURL extension.
