### ISSUE TITLE
error encoding

### ISSUE THREAD

**Issue by pws2016** [parsecsv/parsecsv-for-php#97]
Hello,
i use your library to read data from csv but i'm always use differnent encoding csv file and some times i have error!! 
i use this lines:
$csv = new parseCSV();
$enc=mb_detect_encoding(file_get_contents("csv/".$_SESSION['csv_file'])); // in this session i have my csv file name
$csv->encoding($enc);
$csv->auto("csv/".$_SESSION['csv_file']);

when i do this i see empty page! (also how i can display error in my page php?)
Can please help me

**Comment by Fonata** [comment]
Sorry we weren't of help earlier. I'll close this issue now because so much time has passed. 

From the information you provided I'd guess that ``mb_detect_encoding`` is not always right; if your CSVs come from the same source, the encoding is probably the same within each file - that would eliminate the risk of `mb_detect_encoding` getting it wrong.

Feel free to open it again in case you still have problems.
